# Site
name: 'Tôi Làm Tin Sinh'
description: 'Nơi những câu chuyện về Tin Sinh bắt đầu ...'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'demowebsite'
email: 'n.dat@outlook.com'
mailchimp-list: 'https://datnt.us7.list-manage.com/subscribe?u=3be95e9ff8d5d4544fc572811&id=53bec2da30'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
# Authors
authors:
  dat:
    name: Dat
    display_name: Dat T Nguyen
    gravatar: 4c10ff28fe545b751bc552248d938859
    email: n.dat@outlook.com
    web: https://dattn.com/
    twitter: https://dattn.com/
    description: "Dat is a computational biologist, a data scientist specilized in medical science."
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: dat
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]