# Site
name: 'Khoa học dữ liệu - Tin sinh'
description: 'Chia sẽ về khoa học dữ liệu và tin sinh học ...'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
disqus: 'demowebsite'
email: 'n.dat@outlook.com'
mailchimp-list: 'https://datnt.us7.list-manage.com/subscribe?u=3be95e9ff8d5d4544fc572811&id=53bec2da30'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    Dat:
      name:           Dat
      site:           https://dattn.com/
      #avatar:         /assets/images/avata.jpg
      gravatar:       4c10ff28fe545b751bc552248d938859
      bio:            "Hi, I am Dat, the author of dattn.com. I hope you like my blog!"
      email:          n.dat@outlook.com
      twitter:        https://dattn.com/

 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: Dat
      avatar: assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
